// Generated by Wrangler on Tue May 21 2024 15:52:10 GMT+0200 (Central European Summer Time)
// by running `wrangler types`

interface Env {
	ENVIRONMENT: "prd";
	MEDIA_BUCKET: R2Bucket;
	UPLOAD_QUEUE: Queue;
}
