#:schema node_modules/wrangler/config-schema.json
name = "r2-upload-queue"
main = "src/index.ts"
compatibility_date = "2024-05-12"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "prd"

[[queues.consumers]]
queue = "upload-queue-test"
max_batch_size = 1

[[queues.producers]]
binding = "UPLOAD_QUEUE"
queue = "upload-queue-test"

[[r2_buckets]]
binding = "MEDIA_BUCKET"
bucket_name = "media-bucket"
jurisdiction = "eu"
preview_bucket_name = "media-bucket"
